//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIII.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblManagers = new HashSet<tblManager>();
            this.tblReports = new HashSet<tblReport>();
        }
    
        public int employeeId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string jmbg { get; set; }
        public string mail { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string position { get; set; }
        public string accountNumber { get; set; }
        public string username { get; set; }
        public string password { get; set; }

        //not mapping fields
        public string access { get; set; }
        public string sector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblManager> tblManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReport> tblReports { get; set; }
    }
}
