//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIII.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReport
    {
        public int reportId { get; set; }
        public int employeeId { get; set; }
        public System.DateTime reportDate { get; set; }
        public string fullname { get; set; }
        public string project { get; set; }
        public string position { get; set; }
        public int workingHours { get; set; }
    }
}
